### ISSUE TITLE
"let's get started" not linked to filter page 

### ISSUE THREAD

**Issue by shahar-abramovich** [yotamberk/eat-vision#20]
pressing "let's get started" goes directly to diet page 

![image](https://user-images.githubusercontent.com/92845785/192236603-72362973-62af-4e30-b659-00f72d1699f4.png)

goes to 

![image](https://user-images.githubusercontent.com/92845785/192236892-4e5a6928-5c04-4674-a2d2-6d4b550f7473.png)

**Comment by yotamberk** [comment]
Fixed when returned to original filters page
