### ISSUE TITLE
Customers view

### ISSUE THREAD

**Issue by yotamberk** [yotamberk/eat-vision#46]
The customers view is meant for the customers (kitchen and restaurant owners) who have a kitchen/s and need to manage their data. This data includes: kitchen info, menus, categories, dishes.

The view has no sketches for now so you have a free hand in designing it as you see fit for now, and will go a few iterations of designing as we develop it.

The basic view should have the following: 

- [x] a dashboard like view with the tabs of:  dashboard, kitchen info, menus, categories, dishes.
- [x] DISHES TAB - should contain a list of all dishes. A dish contains a form with: id, name, image, price, categories (ids of categories it belongs to), menus (ids of menus), recipe. a recipe is an object with the schema as seen here (pseudo-code):
![image](https://user-images.githubusercontent.com/4319928/202730119-4567ec22-c41e-4db7-a1f8-7afacd1f155d.png)
(we can talk to explain the logics of this schema)
User should be allowed to add, edit or logically delete a dish.
- [x] dashboard - general overview of the restaurant. Not sure exactly what but probably all kinds of cool graphs and plots of dishes that are vegan vs. gluten free, etc. GO WILD!
- [x] KITCHEN INFO TAB - general info of the kitchen: name, logo, website, opening hours, location, etc.
- [x] MENUS TAB - should contain a list of all menus where the custmer is able to add, edit and remove menus. A menu should contain a name, categories pointing at it. In the menu, the user should be able to reorder and add categories.
- [x] the customer can navigate to his different kitchens via a select on the top of the AppBar

You have a free hand to add, change and modify anything you need for the server-side API under v2 folder in the kitchens, dishes, categories and menus  routes.

GOOD LUCK AND HAVE FUN!

**Comment by samuelarbibe** [comment]
As for the schema, is see that the current schema is different.  
```js
{
    "mandatory": [
        {
            "type": "ingredient",
            "id": "rec1rgKdljBKDDBYx"
        },
        {
            "type": "ingredient",
            "id": "recn2OJJxhThBuzQ0"
        },
        {
            "type": "ingredient",
            "id": "rectpZHKSyKnbUYSb"
        },
        {
            "type": "ingredient",
            "id": "rec0kpM82GnTvoxl7"
        }
    ],
    "excludable": [],
    "putaside": [],
    "choice": [],
    "sideDish": [],
    "addableIngredients": [],
    "addableDishes": []
}
```
  
Should I follow the given schema or the current one?

**Comment by yotamberk** [comment]
Current one I guess

**Comment by yotamberk** [comment]
I stand correct.  Go with the new one

**Comment by yotamberk** [comment]
The only field that is missing in the new schema is "putaside". I think you can put it as a boolean field in all components.

**Comment by samuelarbibe** [comment]
Cool.  
Before I make any more progress, is this OK?  
  


```js
{
    "mandatory": [
        {
            "type": "ingredient",
            "id": "recO2Geb5uA0pPjIQ"
        },
        {
            "type": "ingredient",
            "id": "recSzYWgPTFUtKuJE"
        },
        {
            "type": "ingredient",
            "id": "recoLPpaM6J7uRp86"
        },
        {
            "type": "ingredient",
            "id": "rec0kpM82GnTvoxl7"
        }
    ],
    "addable": [
        {
            "type": "ingredient",
            "id": "rec6bNK8BItrNav4p",
            "price": "20"
        }
    ]
}
```  
  

![Screenshot 2022-11-19 at 10 44 03](https://user-images.githubusercontent.com/38098325/202842797-1688cb03-4a15-4f7b-ae19-8d5bcbb241d0.png)

**Comment by yotamberk** [comment]
Looks great!
